name: Litigation Hold Workflow

on:
  workflow_dispatch:

jobs:
  litigation-hold:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Run PowerShell script
      - name: Run Litigation Hold Task
        id: litigation
        uses: azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |
            whoami
            hostname
