name: Litigation Hold Workflow

on:
  workflow_dispatch:

jobs:
  litigation-hold:
    runs-on: windows-latest

    steps:
      # Run PowerShell script
      - name: Run Litigation Hold Task
        shell: pwsh
        run: |
            whoami
            hostname
